#!/usr/bin/env python
#####################################
# Installation module for kubesec
#####################################

# AUTHOR OF MODULE NAME
AUTHOR=""

# DESCRIPTION OF THE MODULE
DESCRIPTION="This module will install/update kubesec - Security risk analysis for Kubernetes resources"

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="GIT"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION=""

# X64 LOCATION
X64_LOCATION=""

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="kubesec"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN="git,golang"

# DEPENDS FOR FEDORA INSTALLS
FEDORA="git,golang"

# DEPENDS FOR ARCHLINUX INSTALLS
ARCHLINUX=""

# COMMANDS TO RUN AFTER
AFTER_COMMANDS="cd {INSTALL_LOCATION},go build,sudo ln -sf {INSTALL_LOCATION}/kubesec /usr/local/bin/kubesec"

# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
LAUNCHER=""

# PREREQ INSTALL MODULES NEEDED FOR THIS TOOL TO WORK PROPERLY
TOOL_DEPEND=""

# DON'T RUN AFTER COMMANDS ON UPDATE
BYPASS_UPDATE="YES"