#!/usr/bin/env python
#####################################
# Installation module for osint-framework
#####################################

# AUTHOR OF MODULE NAME
AUTHOR="lockFALE"

# DESCRIPTION OF THE MODULE
DESCRIPTION="This module will install/update osint-framework - OSINT Framework"

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="GIT"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION="https://github.com/lockfale/osint-framework"

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="osint-framework"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN="git,npm"

# DEPENDS FOR FEDORA INSTALLS
FEDORA="git,npm"

# THIS WILL STILL RUN AFTER COMMANDS EVEN IF ITS ALREADY INSTALLED. USEFUL FOR FILE UPDATES AND WHEN NOT USING GIT OR OTHER APPLICATIONS THAT NEEDS AFTER COMMANDS EACH TIME
BYPASS_UPDATE="NO"

# COMMANDS TO RUN AFTER
AFTER_COMMANDS="cd {INSTALL_LOCATION},npm install"

# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
# cd {INSTALL_LOCATION},sudo npm start,xdg-open http://localhost:8000
LAUNCHER=""

# PREREQ INSTALL MODULES NEEDED FOR THIS TOOL TO WORK PROPERLY
TOOL_DEPEND=""

