#!/usr/bin/env python
#####################################
# Installation module for Windows-PrivEsc-Check
#####################################

# AUTHOR OF MODULE NAME
AUTHOR="pentestmonkey"

# DESCRIPTION OF THE MODULE
DESCRIPTION="This module will install/update Windows-PrivEsc-Check - Privilege Escalation Checker" 

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="GIT"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION="https://github.com/pentestmonkey/windows-privesc-check"

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="windows-privesc-check"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN="git"

# DEPENDS FOR FEDORA INSTALLS
FEDORA="git"

# THIS WILL STILL RUN AFTER COMMANDS EVEN IF ITS ALREADY INSTALLED. USEFUL FOR FILE UPDATES AND WHEN NOT USING GIT OR OTHER APPLICATIONS THAT NEEDS AFTER COMMANDS EACH TIME
BYPASS_UPDATE="NO"

# COMMANDS TO RUN AFTER
AFTER_COMMANDS=""

# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
LAUNCHER=""

# PREREQ INSTALL MODULES NEEDED FOR THIS TOOL TO WORK PROPERLY
TOOL_DEPEND=""

