#!/usr/bin/env python
#####################################
# Installation module for AzureRT
#####################################

# AUTHOR OF MODULE NAME
AUTHOR="mgeeky"

# DESCRIPTION OF THE MODULE
DESCRIPTION="This module will install/update AzureRT - A PowerShell module implementing various Azure Red Team tactics"

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="GIT"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION="https://github.com/mgeeky/AzureRT"

# X64 LOCATION
X64_LOCATION=""

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="azurert"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN="git,powershell"

# DEPENDS FOR FEDORA INSTALLS
FEDORA="git,powershell"

# DEPENDS FOR ARCHLINUX INSTALLS
ARCHLINUX=""

# COMMANDS TO RUN AFTER
AFTER_COMMANDS=""

# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
LAUNCHER=""

# PREREQ INSTALL MODULES NEEDED FOR THIS TOOL TO WORK PROPERLY
TOOL_DEPEND=""

# DON'T RUN AFTER COMMANDS ON UPDATE
BYPASS_UPDATE="YES"